function [obj, pastDataExportPath] = export_past_project_data(obj)
%export_past_project_data Sends commands to the current WB project to
% export its past parameter and design point data.
%   Part of the WBinstance class

fileID = fopen(obj.scriptFilePath, 'w');

% Write header information to the script file
fprintf(fileID, '# encoding: utf-8\n');
fprintf(fileID, '# Release %s\n', obj.workbenchVersion);
fprintf(fileID, '# EXPORT PAST PROJECT DATA - script autogenerated in Matlab.\n');
fprintf(fileID, 'SetScriptVersion(Version="17.1.127")\n');
fprintf(fileID, '\n');

% Write command to script to open relevant project file
fprintf(fileID, 'Open(FilePath="%s")\n', strrep(obj.projectPath, '\', '/'));

% Copy the data export commands into script
localPath = fileparts(mfilename('fullpath'));
dataExportCommands = fileread(fullfile(localPath, '..', 'resources', 'data_export_script.py'));
fprintf(fileID, '%s', dataExportCommands);

% Run script file (ignore timing output)
fclose(fileID);
[obj, ~] = obj.run_workbench_script(false);

% Pass the filepath for the exported data on
pastDataExportPath = [fileparts(obj.projectPath) '\fullDataExport.csv'];

end
