f = open(GetProjectDirectory() + '\\fullDataExport.csv', 'w')
f.write('# Exported Data from an ANSYS Workbench Project:\n')
f.write('# ' + Project.GetProjectFile() + '\n')
f.write('# Automatically generated by MATLAB-ANSYS scripting.\n')
f.write('\n')

designPointList = Parameters.GetAllDesignPoints()
parameterList = Parameters.GetAllParameters()

f.write('DP Name,')
for desi in designPointList:
    f.write(str(desi.Name) + ',')
f.write('\n')
f.write('UpToDate?,')
for desi in designPointList:
    if desi.StateOfParameters == 'UpToDate':
        f.write(str(1) + ',')
    else:
        f.write(str(0) + ',')
f.write('\n')
f.write('Valid?,')
for desi in designPointList:
    if desi.Retained:
        f.write(str(1) + ',')
    else:
        f.write(str(0) + ',')
f.write('\n\n')

f.write('ParamName,')
for para in parameterList:
    f.write(str(para.Name) + ',')
f.write('\n')
f.write('ParamDesc,')
for para in parameterList:
    f.write(str(para.DisplayText) + ',')
f.write('\n')
f.write('ParamUnit,')
for para in parameterList:
    try:
        f.write(str(para.Value.Unit) + ',')
    except:
        f.write('None,')
f.write('\n')
f.write('ParamUsage,')
for para in parameterList:
    f.write(str(para.Usage) + ',')
f.write('\n')
f.write('ParamExpressionType,')
for para in parameterList:
    f.write(str(para.ExpressionType) + ',')
f.write('\n')

for desi in designPointList:
    f.write(str(desi.Name) + ',')
    for para in parameterList:
        if desi.Retained and Parameters.IsParameterInDesignPointUpToDate(DesignPoint=desi, Parameter=para):
            try:
                f.write(str(desi.GetParameterValue(para).Value) + ',')
            except:
                try:
                    f.write(str(desi.GetParameterValue(para)) + ',')
                except:
                    f.write(',')
        else:
            f.write(',')
    f.write('\n')

f.close()
